---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/brickbot
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:8.10
        environment:
          ENV: CI
    working_directory: ~/brickbot
    steps:
      - checkout
      - run:
          name: eslint Test
          command: yarn lint
          prefix: tests
