---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/brickbot
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:8.10
        environment:
          ENV: CI
    working_directory: ~/brickbot
    steps:
      - checkout
      - run:
          name: Install the latest eslint
          command: sudo npm install -g eslint
      - run:
          name: eslint test
          command: yarn lint
          prefix: tests
  endpoints:
    docker:
      - image: circleci/python:3.6.4
        environment:
          ENV: CI
    working_directory: ~/brickbot/tests
    steps:
      - checkout
      - run:
          name: endpoints test
          command: python3 endpoints.py
          prefix: tests
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - lint
    - endpoints
